name: custom_text_engine
description: Custom text engine with hyphenation for Flutter (custom layout, justify, inline elements).
version: 0.1.1
homepage: https://github.com/1bgn/custom_text_engine
repository: https://github.com/1bgn/custom_text_engine
issue_tracker: https://github.com/1bgn/custom_text_engine/issues
environment:
  sdk: ^3.9.0
  flutter: ">=3.0.0"
dependencies:
  flutter:
    sdk: flutter
  quiver: ^3.2.2
  freezed_annotation: ^3.1.0
dev_dependencies:
  build_runner: ^2.10.4
  freezed: ^3.2.3